name: Node.js Package

on:
  push: 
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
    
      - name: Installing Serverless Framework v-2
        run: npm install -g serverless

      - name: Installing all Dependencies
        run: npm install    
        
      - name: Building the site
        run: npm run build
      
      - name: Deploy to AWS
        run: sls deploy
        env: 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    
      
  
  
  
  
  
